### ISSUE TITLE
Event Click Domain In BarChart

### ISSUE THREAD

**Issue by DucLongDTH** [indratrisnar/d_chart#37]
Is there a way to have a touch event on the domain title in DChartBarO

**Comment by indratrisnar** [comment]
In basic chart depend on community_chart_flutter not have event click on
label axis such as domain label. So maybe we are waiting, or you can
request to main repo communitt_chart.

Otherwise, you can full customization using DChartBarCustom which not
depend on community_chart_flutter

Pada Min, 10 Nov 2024 10.58, Nguyen Duc Long ***@***.***>
menulis:

**Comment by indratrisnar** [comment]
unfortunately, there is not bar grouping on DChartBarCustom

Pada Sen, 11 Nov 2024 09.22, Nguyen Duc Long ***@***.***>
menulis:
