### ISSUE TITLE
Combo chart available?

### ISSUE THREAD

**Issue by jasonflaherty** [indratrisnar/d_chart#9]
Hello and thanks for the library! I've been trying to create a bar/line combo, but don't seem to get a good result. Is the combo chart on your radar for development?

**Comment by indratrisnar** [comment]
for combo chart, not yet available. In the future I still don't know
whether I will add it or not. but you can try to make it using package
https://pub.dev/packages/community_charts_flutter

for samples you can see here:
https://google.github.io/charts/flutter/gallery.html

However, because d_chart is based on the community_charts_flutter library,
there is a possibility that combo charts can be implemented on d_chart
based on samples from community_charts_flutter

hope this helps you

Pada tanggal Sab, 4 Feb 2023 pukul 13.51 Jason Flaherty <
***@***.***> menulis:

**Comment by jasonflaherty** [comment]
Thanks for the reply! I'll check it out.

**Comment by indratrisnar** [comment]
Now available
